#include "zcommon.acs"
#include "packapunchmachine.acs"

global int 10 : SecretLevel40;

script 1 enter
{
	ClearInventory();
    zombiepoints = 500;
	GiveInventory("DoomFist", 1);
	GiveInventory("M1911A1",1);
	GiveInventory("Clip",32);
    Thing_ChangeTID(0,900);
}

script "DoorKinoOpen" (void)
{
	if(CheckInventory("YellowCard")){
		Door_Open(11,128);
	}
}

script "Endmap" (void)
{
	SecretLevel40++;
	Teleport_NewMap(100,0, 0);
}